n = str(input("Digite seu nome completo: ")).title().strip()
nome = n.split()
print("Olá prazer em te conhecer!")
print(f"Seu primeiro nome é: {nome[0]}.")
print(f"Seu ultimo nome é: {nome[len(nome)-1]}.")