msg = input("Digite alguma coisa: ")
print(type(msg))
print("É uma palavra? ", msg.isalpha())
print("É um numero? ", msg.isnumeric())
print("É uma alfanumerico? ", msg.isalnum())
print("Só possui espaços? ", msg.isspace())
print("É maiuscula? ", msg.isupper())
print("É minuscula? ", msg.islower())
print("É capitalizada? ", msg.istitle())